<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LIN33001220"><DocLocation><![CDATA[C:\framework\QTP-Hybrid-Framework\QTP-Hybrid-Framework\TestCases\Login]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Login]]></DName>
<Res><![CDATA[Res27]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
ActiveX, Silverlight, WinForms.]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:15]]></Time>
<TimeTick>1676370015</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[login]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:16]]></Time>
<TimeTick>1676370016</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:16]]></Time>
<TimeTick>1676370016</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:18]]></Time>
<TimeTick>1676370018</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA['[ Log in ] link' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:18]]></Time>
<TimeTick>1676370018</TimeTick>
<NodeArgs eType="User" icon="7" nRep="16" status="Passed" >
<Disp><![CDATA['[ Log in ] link' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:18]]></Time>
<TimeTick>1676370018</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:18]]></Time>
<TimeTick>1676370018</TimeTick>
<NodeArgs eType="User" icon="7" nRep="19" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:18]]></Time>
<TimeTick>1676370018</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="22" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:19]]></Time>
<TimeTick>1676370019</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:19]]></Time>
<TimeTick>1676370019</TimeTick>
<NodeArgs eType="User" icon="7" nRep="25" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:19]]></Time>
<TimeTick>1676370019</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="28" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:19]]></Time>
<TimeTick>1676370019</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="30" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:19]]></Time>
<TimeTick>1676370019</TimeTick>
<NodeArgs eType="User" icon="7" nRep="31" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:19]]></Time>
<TimeTick>1676370019</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="34" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:19]]></Time>
<TimeTick>1676370019</TimeTick>
<NodeArgs eType="User" icon="7" nRep="35" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"[&nbsp;Link&nbsp;]"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:40]]></Time>
<TimeTick>1676370040</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = Log out<br>Mercury Class = Link<br>]]></Details>
<Time><![CDATA[14-02-2023 - 15:50:40]]></Time>
<TimeTick>1676370040</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="77" status="Warning" nType="Description" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="76" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"[&nbsp;Link&nbsp;]"&nbsp;object's&nbsp;parent&nbsp;"[&nbsp;Browser&nbsp;]"&nbsp;(class&nbsp;Browser).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:00]]></Time>
<TimeTick>1676370060</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = Demo Web Shop<br>Mercury Class = Browser<br>]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:00]]></Time>
<TimeTick>1676370060</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="86" status="Warning" nType="Parent description" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="85" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:00]]></Time>
<TimeTick>1676370060</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="88" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:00]]></Time>
<TimeTick>1676370060</TimeTick>
<NodeArgs eType="User" icon="7" nRep="89" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:01]]></Time>
<TimeTick>1676370061</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="92" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:01]]></Time>
<TimeTick>1676370061</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="94" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:01]]></Time>
<TimeTick>1676370061</TimeTick>
<NodeArgs eType="User" icon="7" nRep="95" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:01]]></Time>
<TimeTick>1676370061</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="98" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:01]]></Time>
<TimeTick>1676370061</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="100" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:01]]></Time>
<TimeTick>1676370061</TimeTick>
<NodeArgs eType="User" icon="7" nRep="101" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:01]]></Time>
<TimeTick>1676370061</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="104" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:01]]></Time>
<TimeTick>1676370061</TimeTick>
<NodeArgs eType="User" icon="7" nRep="105" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"[&nbsp;Link&nbsp;]"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:22]]></Time>
<TimeTick>1676370082</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = Log out<br>Mercury Class = Link<br>]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:22]]></Time>
<TimeTick>1676370082</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="148" status="Warning" nType="Description" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="147" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;find&nbsp;the&nbsp;"[&nbsp;Link&nbsp;]"&nbsp;object's&nbsp;parent&nbsp;"[&nbsp;Browser&nbsp;]"&nbsp;(class&nbsp;Browser).<br/>Verify&nbsp;that&nbsp;parent&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:42]]></Time>
<TimeTick>1676370102</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = Demo Web Shop<br>Mercury Class = Browser<br>]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:42]]></Time>
<TimeTick>1676370102</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="157" status="Warning" nType="Parent description" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="156" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Email ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:43]]></Time>
<TimeTick>1676370103</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="159" >
<Disp><![CDATA[[ Email ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:43]]></Time>
<TimeTick>1676370103</TimeTick>
<NodeArgs eType="User" icon="7" nRep="160" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:43]]></Time>
<TimeTick>1676370103</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="163" >
<Disp><![CDATA[[ Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ Password ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:43]]></Time>
<TimeTick>1676370103</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="165" >
<Disp><![CDATA[[ Password ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[Email field is available]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:43]]></Time>
<TimeTick>1676370103</TimeTick>
<NodeArgs eType="User" icon="7" nRep="166" status="Passed" >
<Disp><![CDATA[Email field is available]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:43]]></Time>
<TimeTick>1676370103</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="169" >
<Disp><![CDATA[[ Password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:43]]></Time>
<TimeTick>1676370103</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="171" >
<Disp><![CDATA[[ Log in ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[Login button is avaiable]]></Obj>
<Details ><![CDATA[PASSED]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:43]]></Time>
<TimeTick>1676370103</TimeTick>
<NodeArgs eType="User" icon="7" nRep="172" status="Passed" >
<Disp><![CDATA[Login button is avaiable]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ Log in ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:43]]></Time>
<TimeTick>1676370103</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="175" >
<Disp><![CDATA[[ Log in ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA['[ Log in ] button' Clicked]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[14-02-2023 - 15:51:43]]></Time>
<TimeTick>1676370103</TimeTick>
<NodeArgs eType="User" icon="7" nRep="176" status="Passed" >
<Disp><![CDATA['[ Log in ] button' Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"[&nbsp;Link&nbsp;]"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 15:52:04]]></Time>
<TimeTick>1676370124</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Link ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = Log out<br>Mercury Class = Link<br>]]></Details>
<Time><![CDATA[14-02-2023 - 15:52:04]]></Time>
<TimeTick>1676370124</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="219" status="Warning" nType="Description" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="218" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Link ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Browser ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"[&nbsp;Browser&nbsp;]"&nbsp;(of&nbsp;class&nbsp;Browser).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 15:52:45]]></Time>
<TimeTick>1676370165</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ Browser ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Name = Demo Web Shop<br>Mercury Class = Browser<br>]]></Details>
<Time><![CDATA[14-02-2023 - 15:52:45]]></Time>
<TimeTick>1676370165</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="223" status="Warning" nType="Description" >
<Disp><![CDATA[[ Browser ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="222" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ Browser ]]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 15:50:16" eTime="14-02-2023 - 15:52:45" passed="14" failed="6" warnings="6" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Failed" >
<Disp><![CDATA[login Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[Login Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="14-02-2023 - 15:50:15" eTime="14-02-2023 - 15:52:45" passed="14" failed="6" warnings="7" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Login Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>